layout_spectrum: 0.9264232
color:
  saturation: 0.888107
  brandStrength: 0.5891514
  lightness: 0.3586681
  rhythmicContrast: 0.7603915
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.2690655
name: The Dogster
